### ISSUE TITLE
Server Integration test still sometimes do not run in the Fiber

### ISSUE THREAD

**Issue by Sanjo** [Sanjo/meteor-jasmine#145]
```
Error: Meteor code must always run within a Fiber. Try wrapping callbacks that you pass to non-Meteor libraries with Meteor.bindEnvironment.
  at Object.Meteor._nodeCodeMustBeInFiber (/Users/jonas/eventport/eventport/app/.meteor/local/build/programs/server/packages/meteor.js:953:11)
  at [object Object]._.extend.get (/Users/jonas/eventport/eventport/app/.meteor/local/build/programs/server/packages/meteor.js:965:12)
  at withoutInvocation (/Users/jonas/eventport/eventport/app/.meteor/local/build/programs/server/packages/meteor.js:422:28)
  at bindAndCatch (/Users/jonas/eventport/eventport/app/.meteor/local/build/programs/server/packages/meteor.js:431:33)
  at Object._.extend.setTimeout (/Users/jonas/eventport/eventport/app/.meteor/local/build/programs/server/packages/meteor.js:447:23)
  at QueueRunner.clearStack (/Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:553:9)
  at QueueRunner.run (/Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1754:12)
  at /Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1771:16
  at /Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1716:9
  at complete (/Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2067:9)
  at QueueRunner.clearStack (/Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:555:9)
  at QueueRunner.run (/Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1754:12)
  at /Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1771:16
  at /Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1716:9
  at complete (/Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:2067:9)
  at QueueRunner.clearStack (/Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:555:9)
  at QueueRunner.run (/Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1754:12)
  at /Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1771:16
  at /Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1716:9
  at complete (/Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:330:9)
  at QueueRunner.clearStack (/Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:555:9)
  at QueueRunner.run (/Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1754:12)
  at /Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1771:16
  at /Users/jonas/.meteor/packages/sanjo_jasmine/.0.12.1.17s389g++os+web.browser+web.cordova/npm/node_modules/jasmine-core/lib/jasmine-core/jasmine.js:1716:9
  at Transform.<anonymous> (/Users/jonas/eventport/eventport/app/.meteor/local/build/programs/server/packages/velocity_test-proxy.js:1541:11)
  at Transform.emit (events.js:117:20)
  at _stream_readable.js:943:16
  at process._tickDomainCallback (node.js:463:13)
```

The test is an aync one. (Note: XML export test)

**Comment by rjsmith** [comment]
Hi @Sanjo ,

I've hit this same issue in my async server integration tests today.    After several hours investigating, I *think* I have found the root cause: a bug in jasmine  =:-0.  I would appreciate it if you could take a look at this, as this is the very first time I have looked at the jasmine internals.

Look at this line:
https://github.com/jasmine/jasmine/blob/master/src/core/QueueRunner.js#L20

It sets the `setTimeout` and `clearTimeout` methods to be used by async internals of jasmine tests.  If the `attrs.timeout` is not set, it falls back to standard node functions of the same name.  

Now look at this line in the queueRunnerFactory method, which instantiates QueueRunner objects:

https://github.com/jasmine/jasmine/blob/master/src/core/QueueRunner.js#L20

It sets what becomes the `attrs.timer` parameter in the QueueRunner factory... but note that it sets `timer` field, and not `timeout` !!!   So, as far as I can tell, the attempt by sanjo:jasmine to override the standard `setTimeout` and 'clearTimeoutl` methods to the Meteor equivalents will never work for async tests .. Jasmine will always fall back to the node - standard methods.

I proved this in my own app by hacking the jasmine.js file QueueRunner constructor to correct the typo (use `attrs.timer` instead of `attrs.timeout`):

```javascript
  function QueueRunner(attrs) {
    this.queueableFns = attrs.queueableFns || [];
    this.onComplete = attrs.onComplete || function() {};
    this.clearStack = attrs.clearStack || function(fn) {fn();};
    this.onException = attrs.onException || function() {};
    this.catchException = attrs.catchException || function() { return true; };
    this.userContext = attrs.userContext || {};
    this.timer = attrs.timer || {setTimeout: setTimeout, clearTimeout: clearTimeout};
    this.fail = attrs.fail || function() {};
  }

```
and this time, my async server integration tests worked just fine.

What do you reckon?

Cheers,

Richard

**Comment by Sanjo** [comment]
I already use a fork of Jasmine. So I will apply your fix on it later. Thanks for investigating it.

**Comment by Sanjo** [comment]
Should be fixed in 0.12.4. Haven't tested it myself though.

**Comment by rjsmith** [comment]
Hi,

Yeah - looks really good.  I verified I was still seeing the `Meteor code must always run within a Fiber` exception with sanjo:jasmine@0.12.3. Then upgraded to 0.12.4.  After the hot code push, the tests re-ran and reported the expected test failure, instead of the Fibres message.  After fixing the (deliberate) test failure, the test suite then ran successfully to completion.

I guess I should report this on the jasmine repo ....

**Comment by Sanjo** [comment]
I already reported it here: https://github.com/jasmine/jasmine/issues/792

**Comment by rjsmith** [comment]
Cool.  Txs.
