### ISSUE TITLE
ENOENT error during startup

### ISSUE THREAD

**Issue by valpet** [Sanjo/meteor-jasmine#183]
Using the new sanjo:jasmine@0.13.0-rc.2 package with meteor 1.1.0.2 for windows I receive an ENOENT error when I start meteor.

Steps to recreate:
1) create a new project
2) enter the project directory and add the jasmine package
3) start meteor

I receive the following:
```
W20150407-19:24:38.439(2)? (STDERR)
W20150407-19:24:38.439(2)? (STDERR) C:\Users\Peter\AppData\Local\.meteor\package
s\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibe
rs\future.js:278
W20150407-19:24:38.439(2)? (STDERR)
      ^
W20150407-19:24:38.439(2)? (STDERR) Error: ENOENT, lstat 'C:\Users\Peter\Workspa
ce\Test\packages'
W20150407-19:24:38.439(2)? (STDERR)
throw(ex);
W20150407-19:24:38.439(2)? (STDERR)   at Object.Future.wait (C:\Users\Peter\AppD
ata\Local\.meteor\packages\meteor-tool\1.1.3\mt-os.windows.x86_32\dev_bundle\ser
ver-lib\node_modules\fibers\future.js:398:15)
W20150407-19:24:38.439(2)? (STDERR)   at Object.wrapper [as lstat] (C:\Users\Pet
er\Workspace\Test\.meteor\local\build\programs\server\packages\velocity_meteor-i
nternals.js:452:24)
W20150407-19:24:38.455(2)? (STDERR)   at _initFileWatcher (C:\Users\Peter\Worksp
ace\Test\.meteor\local\build\programs\server\packages\velocity_core.js:703:15)
W20150407-19:24:38.455(2)? (STDERR)   at initializeVelocity (C:\Users\Peter\Work
space\Test\.meteor\local\build\programs\server\packages\velocity_core.js:207:7)
W20150407-19:24:38.455(2)? (STDERR)   at C:\Users\Peter\Workspace\Test\.meteor\l
ocal\build\programs\server\boot.js:229:5
W20150407-19:24:38.455(2)? (STDERR)
W20150407-19:24:38.455(2)? (STDERR)     - - - - -
W20150407-19:24:38.455(2)? (STDERR)
W20150407-19:24:38.455(2)? (STDERR)
=> Exited with code: 8
```

**Comment by valpet** [comment]
I tried updating and found versions 0.13.0-rc.3 and 0.13.0-rc.4 and tried them both but with the same result as described above.

**Comment by Sanjo** [comment]
Fixed with velocity:core:0.6.0-rc.6

**Comment by valpet** [comment]
I'm sorry but i still get the error. 
My packages in my minimal testing project are:
```
autopublish      1.0.3  Publish the entire database to all clients
insecure         1.0.3  Allow all database writes by default
meteor-platform  1.2.2  Include a standard set of Meteor packages in you...
sanjo:jasmine    0.13.0-rc.4  Easily use Jasmine in Meteor
velocity:core    0.6.0-rc.6* Velocity, a Meteor specific test-runner
```

**Comment by Sanjo** [comment]
Thanks for reporting this. This fix is now in 0.6.0-rc.7. Somehow a push on my Windows machine has failed. So the commits weren't in.

**Comment by valpet** [comment]
Tested and verified! Thanks a bunch!
